
export enum MoveScoresEnum {
    FROM_PILE= 1000,
    ADD_TO_STACK= 100,
    OPEN_A_SPACE= 9,
    PLAY_FROM_HAND= 5,
    PLAY_FROM_STACK= 4,
    DISCARD_IN_SEQUENCE= 1,
    DISCARD_OUT_OF_SEQUENCE= 0
}
